---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args: ['--args=--sort-by required']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: detect-private-key
        # excludes
        #exclude: 'path/file'
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.28.1
    hooks:
      - id: talisman-commit
        entry: cmd --githook pre-commit
